/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WaybilltrackingImport } from './routes/waybill_tracking'
import { Route as OrdermgtImport } from './routes/order_mgt'
import { Route as FinancialImport } from './routes/financial'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AddressbookImport } from './routes/address_book'
import { Route as IndexImport } from './routes/index'
import { Route as OrdermgtOrderlistImport } from './routes/order_mgt.order_list'
import { Route as OrdermgtOrdercreateImport } from './routes/order_mgt.order_create'
import { Route as R769VideoImport } from './routes/769.video'
import { Route as R769QuestionnaireImport } from './routes/769.questionnaire'
import { Route as R769CoursewareImport } from './routes/769.courseware'

// Create/Update Routes

const WaybilltrackingRoute = WaybilltrackingImport.update({
  id: '/waybill_tracking',
  path: '/waybill_tracking',
  getParentRoute: () => rootRoute,
} as any)

const OrdermgtRoute = OrdermgtImport.update({
  id: '/order_mgt',
  path: '/order_mgt',
  getParentRoute: () => rootRoute,
} as any)

const FinancialRoute = FinancialImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AddressbookRoute = AddressbookImport.update({
  id: '/address_book',
  path: '/address_book',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrdermgtOrderlistRoute = OrdermgtOrderlistImport.update({
  id: '/order_list',
  path: '/order_list',
  getParentRoute: () => OrdermgtRoute,
} as any)

const OrdermgtOrdercreateRoute = OrdermgtOrdercreateImport.update({
  id: '/order_create',
  path: '/order_create',
  getParentRoute: () => OrdermgtRoute,
} as any)

const R769VideoRoute = R769VideoImport.update({
  id: '/769/video',
  path: '/769/video',
  getParentRoute: () => rootRoute,
} as any)

const R769QuestionnaireRoute = R769QuestionnaireImport.update({
  id: '/769/questionnaire',
  path: '/769/questionnaire',
  getParentRoute: () => rootRoute,
} as any)

const R769CoursewareRoute = R769CoursewareImport.update({
  id: '/769/courseware',
  path: '/769/courseware',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/address_book': {
      id: '/address_book'
      path: '/address_book'
      fullPath: '/address_book'
      preLoaderRoute: typeof AddressbookImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialImport
      parentRoute: typeof rootRoute
    }
    '/order_mgt': {
      id: '/order_mgt'
      path: '/order_mgt'
      fullPath: '/order_mgt'
      preLoaderRoute: typeof OrdermgtImport
      parentRoute: typeof rootRoute
    }
    '/waybill_tracking': {
      id: '/waybill_tracking'
      path: '/waybill_tracking'
      fullPath: '/waybill_tracking'
      preLoaderRoute: typeof WaybilltrackingImport
      parentRoute: typeof rootRoute
    }
    '/769/courseware': {
      id: '/769/courseware'
      path: '/769/courseware'
      fullPath: '/769/courseware'
      preLoaderRoute: typeof R769CoursewareImport
      parentRoute: typeof rootRoute
    }
    '/769/questionnaire': {
      id: '/769/questionnaire'
      path: '/769/questionnaire'
      fullPath: '/769/questionnaire'
      preLoaderRoute: typeof R769QuestionnaireImport
      parentRoute: typeof rootRoute
    }
    '/769/video': {
      id: '/769/video'
      path: '/769/video'
      fullPath: '/769/video'
      preLoaderRoute: typeof R769VideoImport
      parentRoute: typeof rootRoute
    }
    '/order_mgt/order_create': {
      id: '/order_mgt/order_create'
      path: '/order_create'
      fullPath: '/order_mgt/order_create'
      preLoaderRoute: typeof OrdermgtOrdercreateImport
      parentRoute: typeof OrdermgtImport
    }
    '/order_mgt/order_list': {
      id: '/order_mgt/order_list'
      path: '/order_list'
      fullPath: '/order_mgt/order_list'
      preLoaderRoute: typeof OrdermgtOrderlistImport
      parentRoute: typeof OrdermgtImport
    }
  }
}

// Create and export the route tree

interface OrdermgtRouteChildren {
  OrdermgtOrdercreateRoute: typeof OrdermgtOrdercreateRoute
  OrdermgtOrderlistRoute: typeof OrdermgtOrderlistRoute
}

const OrdermgtRouteChildren: OrdermgtRouteChildren = {
  OrdermgtOrdercreateRoute: OrdermgtOrdercreateRoute,
  OrdermgtOrderlistRoute: OrdermgtOrderlistRoute,
}

const OrdermgtRouteWithChildren = OrdermgtRoute._addFileChildren(
  OrdermgtRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address_book': typeof AddressbookRoute
  '/dashboard': typeof DashboardRoute
  '/financial': typeof FinancialRoute
  '/order_mgt': typeof OrdermgtRouteWithChildren
  '/waybill_tracking': typeof WaybilltrackingRoute
  '/769/courseware': typeof R769CoursewareRoute
  '/769/questionnaire': typeof R769QuestionnaireRoute
  '/769/video': typeof R769VideoRoute
  '/order_mgt/order_create': typeof OrdermgtOrdercreateRoute
  '/order_mgt/order_list': typeof OrdermgtOrderlistRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address_book': typeof AddressbookRoute
  '/dashboard': typeof DashboardRoute
  '/financial': typeof FinancialRoute
  '/order_mgt': typeof OrdermgtRouteWithChildren
  '/waybill_tracking': typeof WaybilltrackingRoute
  '/769/courseware': typeof R769CoursewareRoute
  '/769/questionnaire': typeof R769QuestionnaireRoute
  '/769/video': typeof R769VideoRoute
  '/order_mgt/order_create': typeof OrdermgtOrdercreateRoute
  '/order_mgt/order_list': typeof OrdermgtOrderlistRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/address_book': typeof AddressbookRoute
  '/dashboard': typeof DashboardRoute
  '/financial': typeof FinancialRoute
  '/order_mgt': typeof OrdermgtRouteWithChildren
  '/waybill_tracking': typeof WaybilltrackingRoute
  '/769/courseware': typeof R769CoursewareRoute
  '/769/questionnaire': typeof R769QuestionnaireRoute
  '/769/video': typeof R769VideoRoute
  '/order_mgt/order_create': typeof OrdermgtOrdercreateRoute
  '/order_mgt/order_list': typeof OrdermgtOrderlistRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address_book'
    | '/dashboard'
    | '/financial'
    | '/order_mgt'
    | '/waybill_tracking'
    | '/769/courseware'
    | '/769/questionnaire'
    | '/769/video'
    | '/order_mgt/order_create'
    | '/order_mgt/order_list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address_book'
    | '/dashboard'
    | '/financial'
    | '/order_mgt'
    | '/waybill_tracking'
    | '/769/courseware'
    | '/769/questionnaire'
    | '/769/video'
    | '/order_mgt/order_create'
    | '/order_mgt/order_list'
  id:
    | '__root__'
    | '/'
    | '/address_book'
    | '/dashboard'
    | '/financial'
    | '/order_mgt'
    | '/waybill_tracking'
    | '/769/courseware'
    | '/769/questionnaire'
    | '/769/video'
    | '/order_mgt/order_create'
    | '/order_mgt/order_list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressbookRoute: typeof AddressbookRoute
  DashboardRoute: typeof DashboardRoute
  FinancialRoute: typeof FinancialRoute
  OrdermgtRoute: typeof OrdermgtRouteWithChildren
  WaybilltrackingRoute: typeof WaybilltrackingRoute
  R769CoursewareRoute: typeof R769CoursewareRoute
  R769QuestionnaireRoute: typeof R769QuestionnaireRoute
  R769VideoRoute: typeof R769VideoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressbookRoute: AddressbookRoute,
  DashboardRoute: DashboardRoute,
  FinancialRoute: FinancialRoute,
  OrdermgtRoute: OrdermgtRouteWithChildren,
  WaybilltrackingRoute: WaybilltrackingRoute,
  R769CoursewareRoute: R769CoursewareRoute,
  R769QuestionnaireRoute: R769QuestionnaireRoute,
  R769VideoRoute: R769VideoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/address_book",
        "/dashboard",
        "/financial",
        "/order_mgt",
        "/waybill_tracking",
        "/769/courseware",
        "/769/questionnaire",
        "/769/video"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/address_book": {
      "filePath": "address_book.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/financial": {
      "filePath": "financial.tsx"
    },
    "/order_mgt": {
      "filePath": "order_mgt.tsx",
      "children": [
        "/order_mgt/order_create",
        "/order_mgt/order_list"
      ]
    },
    "/waybill_tracking": {
      "filePath": "waybill_tracking.tsx"
    },
    "/769/courseware": {
      "filePath": "769.courseware.tsx"
    },
    "/769/questionnaire": {
      "filePath": "769.questionnaire.tsx"
    },
    "/769/video": {
      "filePath": "769.video.tsx"
    },
    "/order_mgt/order_create": {
      "filePath": "order_mgt.order_create.tsx",
      "parent": "/order_mgt"
    },
    "/order_mgt/order_list": {
      "filePath": "order_mgt.order_list.tsx",
      "parent": "/order_mgt"
    }
  }
}
ROUTE_MANIFEST_END */
